language: c

os:
    - linux
    - osx

notifications:
  email: false

env:
  matrix:
    - PYTHON_VERSION=2.7 MPL_VERSION=1.4 ASTROPY_VERSION=1.0 QT_PKG=pyside
    - PYTHON_VERSION=3.4 MPL_VERSION=1.4 ASTROPY_VERSION=1.0 QT_PKG=pyqt
  global:
    - PYTEST_ARGS="--cov glue"
    - NUMPY_VERSION=1.9
    - IPYTHON_VERSIONSION=4
    - NO_CFG_FILES=false
    - CONDA_DEPENDENCIES="pip scipy cython h5py pygments pyzmq scikit-image pandas sphinx=1.2.3 xlrd pillow pytest mock coverage pyyaml requests sphinx_rtd_theme"
    - PIP_DEPENDENCIES="pytest-cov coveralls pyavm astrodendro awscli"
    - secure: NvQVc3XmmjXNVKrmaD31IgltsOImlnt3frAl4wU0pM223iejr7V57hz/V5Isx6sTANWEiRBMG27v2T8e5IiB7DQTxFUleZk3DWXQV1grw/GarEGUawXAgwDWpF0AE/7BRVJYqo2Elgaqf28+Jkun8ewvfPCiEROD2jWEpnZj+IQ=
    - secure: "SU9BYH8d9eNigypG3lC83s0NY6Mq9AHGKXyEGeXDtz1npJIC1KHdzPMP1v1K3dzCgl1p6ReMXPjZMCENyfNkad/xvzTzGk0Nu/4BjihrUPV6+ratVeLpv0JLm8ikh8q+sZURkdtzUOlds+Hfn5ku4LdpT87tcKHY9TINAGA34ZM="
    - AWS_ACCESS_KEY_ID: AKIAI2ERWDHLW3W24X3A
    - AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY_ID

matrix:

    include:

        # Python 2.6
        - os: linux
          env:
            - PYTHON_VERSION=2.6 IPYTHON_VERSION=1 MPL_VERSION=1.4 ASTROPY_VERSION=0.4 QT_PKG=pyside

        # Astropy dev
        - os: linux
          env:
            - PYTHON_VERSION=2.7 MPL_VERSION=1.4 ASTROPY_VERSION=dev QT_PKG=pyside

        # The following configuration tests that glue functions with minimal
        # dependencies. The --no-deps is to prevent scipy from getting
        # installed as a pandas dependency.
        - os: linux
          env:
            - PYTHON_VERSION=2.7
            - PYTEST_ARGS="--cov glue"
            - CONDA_DEPENDENCIES="pip setuptools=7.0 numpy=$NUMPY_VER pandas mock pbr six funcsigs --no-deps"
            - IPYTHON_VERSION=None
            - ASTROPY_VERSION=None
            - MPL_VERSION=1.4
            - PIP_DEPENDENCIES="pytest-cov coveralls"
            - QT_PKG=pyqt

        - os: linux
          env:
            - PYTHON_VERSION=2.7
            - MPL_VERSION=1.4
            - ASTROPY_VERSION=1.0
            - DOC_TRIGGER=1
            - APP_TRIGGER=1
            - GINGA=1
            - PYTEST_ARGS="--cov glue --no-optional-skip"
            - QT_PKG=pyside
            - NO_CFG_FILES=true

        # Test with older package versions:

        - os: linux
          env: PYTHON_VERSION=2.7 MPL_VERSION=1.3 ASTROPY_VERSION=0.3 NUMPY_VER=1.8 QT_PKG=pyqt

        - os: linux
          env: PYTHON_VERSION=2.7 MPL_VERSION=1.4 ASTROPY_VERSION=0.4 IPYTHON_VERSION=1.1 QT_PKG=pyqt

        - os: linux
          env: PYTHON_VERSION=2.7 MPL_VERSION=1.4 ASTROPY_VERSION=0.4 IPYTHON_VERSION=0.13 QT_PKG=pyqt


before_install:

  # Prepare dependency list
  - export CONDA_DEPENDENCIES="matplotlib=$MPL_VERSION $QT_PKG "$CONDA_DEPENDENCIES

  # Special cases depending on IPython version
  - if [[ $PYTHON_VERSION == 2.6 && $IPYTHON_VERSION == 2 ]]; then export IPYTHON_VERSION=1; fi
  - if [[ $IPYTHON_VERSION != None ]]; then export CONDA_DEPENDENCIES="IPython=$IPYTHON_VERSION "$CONDA_DEPENDENCIES; fi
  - if [[ $IPYTHON_VERSION == 4 ]]; then export CONDA_DEPENDENCIES="qtconsole ipykernel "$CONDA_DEPENDENCIES; fi

  # Documentation dependencies
  - if [ $DOC_TRIGGER ]; then export PIP_DEPENDENCIES="astropy-helpers linkchecker "$PIP_DEPENDENCIES; fi

  # Install ci-helpers and set up conda
  - git clone git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh

  # Deal with issue on Travis builders
  - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo rm -rf /dev/shm; sudo ln -s /run/shm /dev/shm; fi

  # Setup system for headless GUI handling
  - if [[ $TRAVIS_OS_NAME == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi

  # setup tools to trigger mac buildbot
  - if [ $APP_TRIGGER ]; then source .setup_app_trigger.sh; fi
  - if [ $TRAVIS_BRANCH = master ]; then export S3_DIR=latest; else export S3_DIR=$TRAVIS_BRANCH; fi

  # now set up a plugin configuration file with some plugins disabled. This is
  # to make sure that when we run the tests, glue will ignore this
  # configuration and will instead run tests for all plugins.
  - if [[ $NO_CFG_FILES == false ]]; then mkdir ~/.glue; printf "[plugins]\nspectrum_tool = 0\n" >> ~/.glue/plugins.cfg; fi

install:

  - LC_ALL=C

  # Install latest developer version of Ginga
  - if [[ $GINGA ]]; then pip install $PIP_ARGS https://github.com/glue-viz/ginga/archive/master.zip; fi

  # Uninstall PyQt if we are using PySide
  - if [ $QT_PKG == pyside ]; then conda remove pyqt sip || true; fi

  - python setup.py install

script:
  - py.test $PYTEST_ARGS glue -sv
  - if [ $DOC_TRIGGER ]; then cd doc && make html 2> warnings.log && cd ../ ; fi

  # In the following command, the test -s ensures that warnings are not emitted
  # by the docs build.
  - if [ $DOC_TRIGGER ]; then
      cat doc/warnings.log;
      test ! -s doc/warnings.log;
      linkchecker --ignore-url=".*fontawesome_webfont.*" doc/_build/html;
    fi

after_success:

  # Coverage testing
  - coveralls

  # Trigger the building of the MacOS X app in the Travis-MacGlue repo
  - if [ $APP_TRIGGER ]; then ./.trigger_app_build.sh; fi

  # For any branch (but not pull requests), upload the docs to s3
  - if [[ $DOC_TRIGGER && $TRAVIS_SECURE_ENV_VARS == true && $TRAVIS_PULL_REQUEST == false ]]; then cd doc && make s3 && cd ../; fi

  # For the master branch, also upload the docs to the 'latest' URL
  - if [[ $DOC_TRIGGER && $TRAVIS_SECURE_ENV_VARS == true && $TRAVIS_BRANCH == master && $TRAVIS_PULL_REQUEST == false ]]; then cd doc && make s3latest && cd ../; fi