language: python
python:
  - 2.7

env:
   global:
     - PIP_ARGS="--use-mirrors"
     - PYTEST_ARGS=""
   matrix:
     - MPL_VER=1.2.1 ASTRO_VER=0.2.1 IPYTHON_VER=0.13.2 SETUP_CMD='test'
     - MPL_VER=1.1.1 ASTRO_VER=0.2.1 IPYTHON_VER=0.13.2 SETUP_CMD='test'
     - MPL_VER=1.2.1 ASTRO_VER=0.2.1 IPYTHON_VER=0.12.1 PYTEST_ARGS="-s" SETUP_CMD='test'
     - MPL_VER=1.1.1 ASTRO_VER=0.2.1 IPYTHON_VER=0.12.1 PYTEST_ARGS="-s" SETUP_CMD='test'
     - MPL_VER=1.2.1 ASTRO_VER=0.2.1 IPYTHON_VER=0.13.2 SETUP_CMD='cov'


before_install:
  - deactivate
  - virtualenv --system-site-packages ~/virtualenv/this
  - source ~/virtualenv/this/bin/activate

  - sudo apt-get install -qq python-scipy python-qt4 pyqt4-dev-tools python-h5py

# Run GUIs in headless mode
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install $PIP_ARGS numpy
  - pip install $PIP_ARGS astropy==$ASTRO_VER
  - pip install $PIP_ARGS IPython==$IPYTHON_VER
  - pip install $PIP_ARGS matplotlib==$MPL_VER
  - pip install $PIP_ARGS pygments pyzmq
  - pip install $PIP_ARGS mock pytest pyavm cython h5py
  - pip install --use-mirrors scikit-image
  - python setup.py build
  - if [[ $SETUP_CMD == cov ]]; then pip install pytest -q --use-mirrors; fi
  - if [[ $SETUP_CMD == cov ]]; then pip install pytest-cov -q --use-mirrors; fi
  - if [[ $SETUP_CMD == cov ]]; then pip install coveralls -q --use-mirrors; fi



script:
  - if [[ $SETUP_CMD == test ]]; then py.test $PYTEST_ARGS glue; fi
  - if [[ $SETUP_CMD == cov ]]; then py.test --cov glue glue; fi

after_success:
  - if [[ $SETUP_CMD == cov ]]; then coveralls; fi