language: python
python:
  - 2.7

env:
   global:
     - PIP_ARGS="--use-mirrors"
     - PYTEST_ARGS=""
     - BASE_DEPS="numpy mock pytest pyavm cython h5py pygments pyzmq"
   matrix:
     # current versions of everything
     - MPL_VER=1.3.1 ASTRO_VER=0.3.0 IPYTHON_VER=1.1.0 SETUP_CMD='test'

     # old MPL
     - MPL_VER=1.2.1 ASTRO_VER=0.3.0 IPYTHON_VER=1.1.0 SETUP_CMD='test'
     - MPL_VER=1.1.1 ASTRO_VER=0.3.0 IPYTHON_VER=1.1.0 SETUP_CMD='test'

     # old astropy
     - MPL_VER=1.3.1 ASTRO_VER=0.2.5 IPYTHON_VER=1.1.0 SETUP_CMD='test'

     # old ipython
     - MPL_VER=1.3.1 ASTRO_VER=0.3.0 IPYTHON_VER=1.1.0 SETUP_CMD='test'
     - MPL_VER=1.3.1 ASTRO_VER=0.3.0 IPYTHON_VER=1.0.0 SETUP_CMD='test'
     - MPL_VER=1.3.1 ASTRO_VER=0.3.0 IPYTHON_VER=0.13.2 SETUP_CMD='test'

     # coverage
     - MPL_VER=1.3.1 ASTRO_VER=0.3.0 IPYTHON_VER=1.1.0 SETUP_CMD='cov'


before_install:
  - deactivate
  - virtualenv --system-site-packages ~/virtualenv/this
  - source ~/virtualenv/this/bin/activate
  - sudo apt-get install -qq python-scipy python-qt4 pyqt4-dev-tools python-h5py

# Run GUIs in headless mode
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - pip install $PIP_ARGS $BASE_DEPS
  - pip install $PIP_ARGS astropy==$ASTRO_VER
  - pip install $PIP_ARGS IPython==$IPYTHON_VER
  - pip install $PIP_ARGS matplotlib==$MPL_VER
  - pip install $PIP_ARGS scikit-image  # must be installed after cython
  - python setup.py build
  - if [[ $SETUP_CMD == cov ]]; then pip install pytest-cov -q --use-mirrors; fi
  - if [[ $SETUP_CMD == cov ]]; then pip install coveralls -q --use-mirrors; fi



script:
  - if [[ $SETUP_CMD == test ]]; then py.test $PYTEST_ARGS glue; fi
  - if [[ $SETUP_CMD == cov ]]; then py.test --cov glue glue; fi

after_success:
  - if [[ $SETUP_CMD == cov ]]; then coveralls; fi